In [2]:
import pandas as pd
import numpy as np

In [3]:
first_series = pd.Series()

In [4]:
first_series = pd.Series({'1':'Ahmedabad', '2':'Bangalore', '3':'Chennai','4':'Delhi','5':'Kolkatta','6':'Mumbai'})
print(first_series)

1    Ahmedabad
2    Bangalore
3      Chennai
4        Delhi
5     Kolkatta
6       Mumbai
dtype: object

In [5]:
second_series = pd.Series(np.arange(5,13,2))
print(second_series)

0     5
1     7
2     9
3    11
dtype: int32

In [6]:
third_series = pd.Series(['Mango','Apple','Banana','Orange','Grape'])
print(third_series)

0     Mango
1     Apple
2    Banana
3    Orange
4     Grape
dtype: object

In [7]:
print(third_series.index)

RangeIndex(start=0, stop=5, step=1)

In [8]:
first_df = pd.DataFrame({'A':[1,2,3,4], 'B':[8,7,6,5], 'C':[9,12,11,10]})
print(first_df)

   A  B   C
0  1  8   9
1  2  7  12
2  3  6  11
3  4  5  10

In [9]:
market_data = pd.read_csv('C:/Users/VKAMIRE/Documents/HD/Python/Python/Datasets/global_sales/market_fact.csv')

FileNotFoundError: File b'C:/Users/VKAMIRE/Documents/HD/Python/Python/Datasets/global_sales/market_fact.csv' does not exist

In [11]:
type(market_data)

pandas.core.frame.DataFrame

In [12]:
market_data.head()

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.81,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.27,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.30,0.38

In [13]:
market_data.tail(10)

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
8389,Ord_4444,Prod_13,SHP_6192,Cust_1519,159.4100,0.00,44,34.68,0.98,0.52
8390,Ord_5435,Prod_16,SHP_7594,Cust_1798,316.9900,0.04,47,-276.54,8.37,0.58
8391,Ord_5435,Prod_4,SHP_7594,Cust_1798,1991.8985,0.07,20,88.36,7.69,0.58
8392,Ord_5384,Prod_9,SHP_7519,Cust_1798,181.5000,0.08,43,-6.24,2.50,0.37
8393,Ord_5348,Prod_8,SHP_7470,Cust_1798,356.7200,0.07,9,12.61,1.99,0.44
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [14]:
market_data.describe()

,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
count,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8336.000000
mean,1775.878179,0.049671,25.571735,181.184424,12.838557,0.512513
std,3585.050525,0.031823,14.481071,1196.653371,17.264052,0.135589
min,2.240000,0.000000,1.000000,-14140.700000,0.490000,0.350000
25%,143.195000,0.020000,13.000000,-83.315000,3.300000,0.380000
50%,449.420000,0.050000,26.000000,-1.500000,6.070000,0.520000
75%,1709.320000,0.080000,38.000000,162.750000,13.990000,0.590000
max,89061.050000,0.250000,50.000000,27220.690000,164.730000,0.850000

In [15]:
market_data.columns

Index([u'Ord_id', u'Prod_id', u'Ship_id', u'Cust_id', u'Sales', u'Discount',
       u'Order_Quantity', u'Profit', u'Shipping_Cost', u'Product_Base_Margin'],
      dtype='object')

In [16]:
market_data[40:55]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
40,Ord_5035,Prod_15,SHP_7024,Cust_1710,4917.6900,0.02,42,126.31,30.00,0.71
41,Ord_5046,Prod_7,SHP_7041,Cust_1710,202.1100,0.08,40,-17.49,3.39,0.37
42,Ord_1184,Prod_11,SHP_1635,Cust_452,73.4400,0.00,3,-53.78,27.75,0.76
43,Ord_1189,Prod_6,SHP_1641,Cust_452,49.6100,0.00,1,-41.82,17.08,0.40
44,Ord_1184,Prod_1,SHP_1634,Cust_452,1974.6600,0.06,32,-929.68,35.00,0.80
45,Ord_4768,Prod_12,SHP_6650,Cust_1579,3.8500,0.08,1,-1.36,0.99,0.37
46,Ord_4690,Prod_2,SHP_6545,Cust_1579,904.1200,0.07,4,28.81,11.79,0.42
47,Ord_4659,Prod_6,SHP_6493,Cust_1579,1451.5900,0.06,26,435.11,14.30,0.37
48,Ord_4622,Prod_12,SHP_6437,Cust_1579,56.2600,0.00,14,28.11,0.50,0.38
49,Ord_4657,Prod_5,SHP_6490,Cust_1579,336.8600,0.06,23,36.32,5.30,0.46
50,Ord_4682,Prod_5,SHP_6531,Cust_1579,63.9100,0.04,14,-44.47,6.60,0.49
51,Ord_4768,Prod_4,SHP_6651,Cust_1579,547.0005,0.08,10,-97.20,3.90,0.55
52,Ord_4755,Prod_13,SHP_6628,Cust_1579,3.4100,0.06,1,-1.78,0.70,0.56
53,Ord_4659,Prod_6,SHP_6492,Cust_1579,391.9000,0.10,11,-47.01,19.99,0.38
54,Ord_4682,Prod_4,SHP_6531,Cust_1579,1909.0065,0.01,32,344.13,8.99,0.59

In [17]:
market_data_facts = market_data[['Discount','Order_Quantity','Profit','Shipping_Cost','Product_Base_Margin']]
market_data_facts.head()
market_data_facts.rename(columns={'Discount':'DSC'})

       DSC  Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin
0     0.01              23   -30.51           3.60                 0.56
1     0.01              13     4.56           0.93                 0.54
2     0.00              26  1148.90           2.50                 0.59
3     0.09              43   729.34          14.30                 0.37
4     0.08              35  1219.87          26.30                 0.38
5     0.03              23   -47.64           6.15                 0.37
6     0.01               5     1.32           0.50                 0.36
7     0.10              48  1137.91           0.99                 0.55
8     0.01              33    45.84           0.71                 0.52
9     0.07               8   -27.72           6.60                 0.37
10    0.01              43  1675.98           0.99                 0.56
11    0.05              38    79.34           4.86                 0.38
12    0.04              27    23.12           3.37                 0.57
13    0.10              15  -693.23          61.76                 0.78
14    0.08              10  -317.48          36.09                 0.77
15    0.06              48  -103.48           7.29                 0.45
16    0.06              30   193.12           1.39                 0.38
17    0.02              25  4089.27          26.00                 0.60
18    0.08              45  -141.26           6.81                 0.36
19    0.05              12   -37.03           4.20                 0.56
20    0.08              18   -24.03           2.31                 0.56
21    0.01              11   -44.54           7.86                 0.37
22    0.09              44   991.26          19.99                 0.43
23    0.05              10    -0.71           1.63                 0.36
24    0.08              13     3.46           7.27                 0.38
25    0.03              22    -2.34           0.70                 0.56
26    0.00              13    31.32           4.00                 0.42
27    0.01              28   401.80           6.66                 0.40
28    0.05              38  1016.97           2.50                 0.55
29    0.07              33  -140.54           6.89                 0.39
...    ...             ...      ...            ...                  ...
8369  0.02              41   515.62           1.49                 0.38
8370  0.04              20   -17.75           2.03                 0.57
8371  0.07              28  1049.54           8.99                 0.58
8372  0.03               7    12.64           1.39                 0.36
8373  0.10              30   -31.95           1.32                 0.83
8374  0.08              14  -256.93          48.20                 0.74
8375  0.10              47   226.53          11.63                 0.37
8376  0.00              36   -27.99           6.50                 0.79
8377  0.00              12    10.58           0.50                 0.39
8378  0.05              20   312.52           3.50                 0.59
8379  0.04              41    69.31           8.99                 0.50
8380  0.04              45  -143.58           7.37                 0.37
8381  0.01              25   561.13           8.99                 0.59
8382  0.00              28   -92.85           5.34                 0.38
8383  0.04              21  -546.98          35.00                 0.85
8384  0.04              10   -56.30           7.78                 0.37
8385  0.04              46   100.22           4.98                 0.40
8386  0.07              39    11.32           1.35                 0.40
8387  0.04               4   -16.39           6.28                 0.35
8388  0.03              10  -335.06          35.00                  NaN
8389  0.00              44    34.68           0.98                 0.52
8390  0.04              47  -276.54           8.37                 0.58
8391  0.07              20    88.36           7.69                 0.58
8392  0.08              43    -6.24           2.50                 0.37
8393  0.07               9    12.61           1.99                 0.44
8394  0.08              28   374.63           7.69                 0.59
8395  0.10              20   -74.03           6.92                 0.37
8396  0.02              39   -70.85           5.35                 0.40
8397  0.03              23   565.34          30.00                 0.62
8398  0.00              47   131.39           4.86                 0.38

[8399 rows x 5 columns]

In [19]:
market_data_facts

      Discount  Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin
0         0.01              23   -30.51           3.60                 0.56
1         0.01              13     4.56           0.93                 0.54
2         0.00              26  1148.90           2.50                 0.59
3         0.09              43   729.34          14.30                 0.37
4         0.08              35  1219.87          26.30                 0.38
5         0.03              23   -47.64           6.15                 0.37
6         0.01               5     1.32           0.50                 0.36
7         0.10              48  1137.91           0.99                 0.55
8         0.01              33    45.84           0.71                 0.52
9         0.07               8   -27.72           6.60                 0.37
10        0.01              43  1675.98           0.99                 0.56
11        0.05              38    79.34           4.86                 0.38
12        0.04              27    23.12           3.37                 0.57
13        0.10              15  -693.23          61.76                 0.78
14        0.08              10  -317.48          36.09                 0.77
15        0.06              48  -103.48           7.29                 0.45
16        0.06              30   193.12           1.39                 0.38
17        0.02              25  4089.27          26.00                 0.60
18        0.08              45  -141.26           6.81                 0.36
19        0.05              12   -37.03           4.20                 0.56
20        0.08              18   -24.03           2.31                 0.56
21        0.01              11   -44.54           7.86                 0.37
22        0.09              44   991.26          19.99                 0.43
23        0.05              10    -0.71           1.63                 0.36
24        0.08              13     3.46           7.27                 0.38
25        0.03              22    -2.34           0.70                 0.56
26        0.00              13    31.32           4.00                 0.42
27        0.01              28   401.80           6.66                 0.40
28        0.05              38  1016.97           2.50                 0.55
29        0.07              33  -140.54           6.89                 0.39
...        ...             ...      ...            ...                  ...
8369      0.02              41   515.62           1.49                 0.38
8370      0.04              20   -17.75           2.03                 0.57
8371      0.07              28  1049.54           8.99                 0.58
8372      0.03               7    12.64           1.39                 0.36
8373      0.10              30   -31.95           1.32                 0.83
8374      0.08              14  -256.93          48.20                 0.74
8375      0.10              47   226.53          11.63                 0.37
8376      0.00              36   -27.99           6.50                 0.79
8377      0.00              12    10.58           0.50                 0.39
8378      0.05              20   312.52           3.50                 0.59
8379      0.04              41    69.31           8.99                 0.50
8380      0.04              45  -143.58           7.37                 0.37
8381      0.01              25   561.13           8.99                 0.59
8382      0.00              28   -92.85           5.34                 0.38
8383      0.04              21  -546.98          35.00                 0.85
8384      0.04              10   -56.30           7.78                 0.37
8385      0.04              46   100.22           4.98                 0.40
8386      0.07              39    11.32           1.35                 0.40
8387      0.04               4   -16.39           6.28                 0.35
8388      0.03              10  -335.06          35.00                  NaN
8389      0.00              44    34.68           0.98                 0.52
8390      0.04              47  -276.54           8.37                 0.58
8391      0.07              20    88.36           7.69                 0.58
8392      0.08              43    -6.24           2.50                 0.37
8393      0.07               9    12.61           1.99                 0.44
8394      0.08              28   374.63           7.69                 0.59
8395      0.10              20   -74.03           6.92                 0.37
8396      0.02              39   -70.85           5.35                 0.40
8397      0.03              23   565.34          30.00                 0.62
8398      0.00              47   131.39           4.86                 0.38

[8399 rows x 5 columns]

In [18]:
loc_subset = market_data.loc[20:31,'Sales':'Profit']
loc_subset

        Sales  Discount  Order_Quantity   Profit
20    57.1700      0.08              18   -24.03
21    81.2500      0.01              11   -44.54
22  3202.2500      0.09              44   991.26
23    35.6400      0.05              10    -0.71
24   197.6100      0.08              13     3.46
25    38.2600      0.03              22    -2.34
26   109.5800      0.00              13    31.32
27  1062.6900      0.01              28   401.80
28  3594.7435      0.05              38  1016.97
29   139.9800      0.07              33  -140.54
30   129.1000      0.00              27   -59.82
31    68.9200      0.04              22     2.63

In [1]:
loc_subset.sort_index(axis=1, ascending=False,inplace = True)
print(loc_subset)

NameError: name 'loc_subset' is not defined

In [ ]:
help(loc_subset.sort_index)

In [21]:
loc_subset.sort_values(by='Sales',ascending =False,inplace=True)
print(loc_subset)

        Sales  Discount  Order_Quantity   Profit
28  3594.7435      0.05              38  1016.97
22  3202.2500      0.09              44   991.26
27  1062.6900      0.01              28   401.80
24   197.6100      0.08              13     3.46
29   139.9800      0.07              33  -140.54
30   129.1000      0.00              27   -59.82
26   109.5800      0.00              13    31.32
21    81.2500      0.01              11   -44.54
31    68.9200      0.04              22     2.63
20    57.1700      0.08              18   -24.03
25    38.2600      0.03              22    -2.34
23    35.6400      0.05              10    -0.71

In [ ]:
loc_subset.sort_values(by=['Profit','Sales'],ascending =False,inplace=True)
print(loc_subset)

In [22]:
prod_data = pd.read_csv('C:/Users/VKAMIRE/Documents/HD/Python/Python/Datasets/global_sales/prod_dimen.csv')
prod_data.dtypes

Product_Category        object
Product_Sub_Category    object
Prod_id                 object
dtype: object

In [23]:
prod_data['Product_Category'] = prod_data['Product_Category'].astype('category')
print(prod_data.dtypes)

Product_Category        category
Product_Sub_Category      object
Prod_id                   object
dtype: object

In [24]:
combined_data = pd.merge(market_data, prod_data, on='Prod_id', how='outer')
combined_data

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin,Product_Category,Product_Sub_Category
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.81,0.01,23,-30.51,3.60,0.56,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
1,Ord_2978,Prod_16,SHP_4112,Cust_1088,305.05,0.04,27,23.12,3.37,0.57,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
2,Ord_5484,Prod_16,SHP_7663,Cust_1820,322.82,0.05,35,-17.58,3.98,0.56,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
3,Ord_3730,Prod_16,SHP_5175,Cust_1314,459.08,0.04,34,61.57,3.14,0.60,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
4,Ord_4143,Prod_16,SHP_5771,Cust_1417,207.21,0.06,24,-78.64,6.14,0.59,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
5,Ord_4796,Prod_16,SHP_6686,Cust_1659,95.09,0.09,9,-13.53,3.37,0.57,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
6,Ord_1854,Prod_16,SHP_2548,Cust_727,182.47,0.05,17,-3.18,3.37,0.57,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
7,Ord_4506,Prod_16,SHP_6273,Cust_1544,92.02,0.07,9,-24.88,4.68,0.59,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
8,Ord_4080,Prod_16,SHP_5688,Cust_1388,666.40,0.00,39,2.02,7.42,0.56,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
9,Ord_1551,Prod_16,SHP_2145,Cust_531,184.77,0.00,29,-71.96,5.30,0.55,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
10,Ord_1579,Prod_16,SHP_2178,Cust_566,139.37,0.04,16,1.72,2.64,0.59,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
11,Ord_1429,Prod_16,SHP_1976,Cust_510,539.06,0.05,42,-123.07,4.59,0.82,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
12,Ord_2471,Prod_16,SHP_3386,Cust_965,90.93,0.05,43,-72.50,2.56,0.55,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
13,Ord_2873,Prod_16,SHP_3957,Cust_1052,138.55,0.03,16,0.90,2.64,0.59,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
14,Ord_43,Prod_16,SHP_56,Cust_34,9620.82,0.04,6,-1759.58,24.49,0.81,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
15,Ord_956,Prod_16,SHP_1324,Cust_346,503.17,0.01,46,-10.21,4.68,0.59,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
16,Ord_975,Prod_16,SHP_1345,Cust_346,638.91,0.02,49,77.48,3.14,0.60,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
17,Ord_2385,Prod_16,SHP_3273,Cust_939,138.84,0.00,15,8.75,2.64,0.59,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
18,Ord_4307,Prod_16,SHP_6011,Cust_1440,395.37,0.07,37,17.15,3.37,0.57,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
19,Ord_4328,Prod_16,SHP_6033,Cust_1440,103.03,0.07,49,-82.63,2.56,0.55,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
20,Ord_4031,Prod_16,SHP_5613,Cust_1391,171.50,0.02,16,-20.41,4.68,0.59,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
21,Ord_208,Prod_16,SHP_284,Cust_67,327.15,0.04,19,47.30,3.26,0.56,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
22,Ord_1154,Prod_16,SHP_1590,Cust_444,483.64,0.10,45,28.39,3.37,0.57,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
23,Ord_1486,Prod_16,SHP_2052,Cust_513,487.50,0.05,46,-25.88,4.68,0.59,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
24,Ord_1968,Prod_16,SHP_2692,Cust_1623,576.58,0.04,41,-81.55,7.59,0.56,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
25,Ord_4593,Prod_16,SHP_6388,Cust_1457,413.37,0.04,50,-224.41,7.77,0.55,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
26,Ord_279,Prod_16,SHP_378,Cust_113,399.58,0.04,46,-188.53,7.77,0.55,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
27,Ord_1793,Prod_16,SHP_2484,Cust_826,482.93,0.06,34,-67.59,7.59,0.56,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
28,Ord_104,Prod_16,SHP_142,Cust_62,4.99,0.04,1,-3.06,1.32,0.83,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
29,Ord_5169,Prod_16,SHP_7226,Cust_1757,210.24,0.00,34,-31.67,3.60,0.56,OFFICE SUPPLIES,"SCISSORS, RULERS AND TRIMMERS"
...,...,...,...,...,...,...,...,...,...,...,...,...
8369,Ord_3903,Prod_14,SHP_5417,Cust_1334,3457.99,0.05,1,-11861.46,24.49,0.37,TECHNOLOGY,COPIERS AND FAX
8370,Ord_1699,Prod_14,SHP_2353,Cust_586,10567.45,0.10,38,2925.37,11.64,0.50,TECHNOLOGY,COPIERS AND FAX
8371,Ord_2164,Prod_14,SHP_2950,Cust_812,1294.35,0.06,3,-1569.06,24.49,0.40,TECHNOLOGY,COPIERS AND FAX
8372,Ord_3629,Prod_14,SHP_5026,Cust_1260,13934.53,0.10,50,4352.83,11.64,0.50,TECHNOLOGY,COPIERS AND FAX
8373,Ord_4166,Prod_14,SHP_5804,Cust_1401,21956.03,0.10,38,5903.09,24.49,0.50,TECHNOLOGY,COPIERS AND FAX
8374,Ord_3073,Prod_14,SHP_4267,Cust_1142,3550.28,0.06,1,-11769.17,24.49,0.37,TECHNOLOGY,COPIERS AND FAX
8375,Ord_1791,Prod_14,SHP_2711,Cust_685,21717.36,0.06,32,8249.86,24.49,0.41,TECHNOLOGY,COPIERS AND FAX
8376,Ord_3297,Prod_14,SHP_4573,Cust_1230,13571.70,0.00,29,3825.69,24.49,0.52,TECHNOLOGY,COPIERS AND FAX
8377,Ord_997,Prod_14,SHP_1379,Cust_365,28761.52,0.04,8,285.11,24.49,0.37,TECHNOLOGY,COPIERS AND FAX
8378,Ord_1479,Prod_14,SHP_2042,Cust_522,14240.76,0.06,25,3128.69,24.49,0.50,TECHNOLOGY,COPIERS AND FAX
8379,Ord_1943,Prod_14,SHP_2661,Cust_720,6813.93,0.09,16,358.19,49.00,0.38,TECHNOLOGY,COPIERS AND FAX
8380,Ord_778,Prod_14,SHP_1067,Cust_262,7813.70,0.09,40,2154.33,24.49,0.46,TECHNOLOGY,COPIERS AND FAX
8381,Ord_5391,Prod_14,SHP_7527,Cust_1799,24233.54,0.07,43,6492.67,24.49,0.50,TECHNOLOGY,COPIERS AND FAX
8382,Ord_5425,Prod_14,SHP_7580,Cust_1799,27720.98,0.07,46,11984.40,24.49,0.37,TECHNOLOGY,COPIERS AND FAX
8383,Ord_5018,Prod_14,SHP_7001,Cust_1696,7325.63,0.04,38,1899.23,24.49,0.46,TECHNOLOGY,COPIERS AND FAX
8384,Ord_1265,Prod_14,SHP_1749,Cust_466,24051.49,0.07,41,9791.04,24.49,0.37,TECHNOLOGY,COPIERS AND FAX
8385,Ord_669,Prod_14,SHP_916,Cust_224,20872.16,0.03,29,-4437.91,24.49,0.41,TECHNOLOGY,COPIERS AND FAX
8386,Ord_171,Prod_14,SHP_231,Cust_1194,6350.29,0.02,10,-735.97,24.49,0.50,TECHNOLOGY,COPIERS AND FAX
8387,Ord_1390,Prod_14,SHP_1919,Cust_537,6933.45,0.04,15,1200.21,49.00,0.38,TECHNOLOGY,COPIERS AND FAX
8388,Ord_508,Prod_14,SHP_686,Cust_186,19109.61,0.10,40,-379.29,24.49,0.36,TECHNOLOGY,COPIERS AND FAX
8389,Ord_1767,Prod_14,SHP_2450,Cust_583,16743.76,0.00,23,6079.63,24.49,0.41,TECHNOLOGY,COPIERS AND FAX
8390,Ord_546,Prod_14,SHP_858,Cust_198,27875.54,0.00,46,-635.69,24.49,0.44,TECHNOLOGY,COPIERS AND FAX
8391,Ord_5401,Prod_14,SHP_7543,Cust_1801,10281.79,0.03,20,3272.90,24.49,0.36,TECHNOLOGY,COPIERS AND FAX
8392,Ord_3721,Prod_14,SHP_5162,Cust_1309,614.14,0.09,3,-735.27,24.49,0.46,TECHNOLOGY,COPIERS AND FAX
8393,Ord_4106,Prod_14,SHP_5720,Cust_1397,11829.40,0.07,20,3899.72,24.49,0.37,TECHNOLOGY,COPIERS AND FAX
8394,Ord_5467,Prod_14,SHP_7639,Cust_1803,5964.19,0.10,33,988.20,24.49,0.46,TECHNOLOGY,COPIERS AND FAX
8395,Ord_825,Prod_14,SHP_1132,Cust_247,27663.92,0.05,8,-391.92,24.49,0.37,TECHNOLOGY,COPIERS AND FAX
8396,Ord_5368,Prod_14,SHP_7497,Cust_1795,17279.62,0.04,40,4176.25,24.49,0.52,TECHNOLOGY,COPIERS AND FAX
8397,Ord_1765,Prod_14,SHP_2446,Cust_595,14647.26,0.07,25,5485.15,24.49,0.37,TECHNOLOGY,COPIERS AND FAX
8398,Ord_3610,Prod_14,SHP_4998,Cust_1266,1759.65,0.06,3,-2213.75,24.49,0.50,TECHNOLOGY,COPIERS AND FAX

In [ ]:
cust_data = pd.read_csv('C:/Users/VKAMIRE/Documents/HD/Python/Python/Datasets/global_sales/cust_dimen.csv')
ship_data = pd.read_csv('C:/Users/VKAMIRE/Documents/HD/Python/Python/Datasets/global_sales/shipping_dimen.csv')

combined_data2 = pd.merge(combined_data, cust_data, on = 'Cust_id',how='outer')
combined_master = pd.merge(combined_data2, ship_data, on = 'Ship_id', how='outer')
combined_master

In [ ]:
# Horizontal Subset
#get number of observations with a profit greater than 1000
profit_grt_1000 = combined_master[combined_master.Profit > 1000]
profit_grt_1000_counts = len(profit_grt_1000)
print(profit_grt_1000_counts)
profit_grt_1000

In [ ]:
high_value = combined_master.query('Sales >1000 and Order_Quantity <30')
high_value

In [ ]:
help(combined_master.where)

In [ ]:
#Using where

high_value_where = combined_master.where(combined_master.Sales >1000,-combined_master)
high_value_where

In [ ]:
print(len(high_value_where))
print(len(high_value_where.dropna(axis=0)))

In [ ]:
print(combined_master.Product_Category.dtype)
combined_master['Product_Category'] = combined_master['Product_Category'].astype('category')

print(combined_master.Product_Category.dtype)

In [ ]:
combined_master

In [ ]:
combined_master.groupby(['Product_Category'])['Sales'].mean()

In [ ]:
combined_master.groupby(['Product_Category','Product_Sub_Category'])[['Sales','Profit']].mean()

In [ ]:
combined_master.groupby(['Product_Category','Product_Sub_Category'])[['Sales','Profit']].count()

In [ ]:
combined_master.groupby(['Product_Category','Product_Sub_Category'])[['Sales','Profit']].sum()

In [ ]:
groupings = combined_master.groupby(['Product_Category','Region'])

In [ ]:
groupings.agg([np.sum, np.mean, np.std])

In [ ]:
groupings.agg([np.sum, np.mean, np.std])['Order_Quantity']

In [ ]:
pivot_ex = combined_master.drop_duplicates(subset = 'Ship_Date', inplace = False)

In [ ]:
def get_id(any_id):
    out = any_id.split('_')[1]
    return out

In [ ]:
get_id_lambda = lambda x : x.split('_')[1]

In [ ]:
combined_master['Cust_id_new'] = combined_master['Cust_id'].apply(get_id)
combined_master['Ord_id_new'] = combined_master['Ord_id'].apply(get_id_lambda)

combined_master.head()

In [ ]:
combined_master.to_csv('combined.csv')

In [ ]:
year=[1,1000,1500,1650,1750,1804,1850,1900,1927,1950,1955,1960,1965,1970,1975,1980,1985,1990,1995,1999,2006,2009,2011,2025,2043,2083
]

In [ ]:
pop=[0.2,0.275,0.45,0.5,0.7,1,1.2,1.6,2,2.55,2.8,3,3.3,3.7,4,4.5,4.85,5.3,5.7,6,6.5,6.8,7,8,9,10]

In [ ]:
import matplotlib.pyplot as plt
#help(plt.plot)

In [ ]:
plt.plot(year,pop)
plt.show()

In [ ]:
plt.scatter(year,pop)
plt.show()

In [ ]:
life_exp=[43.828000000000003,
 76.423000000000002,
 72.301000000000002,
 42.731000000000002,
 75.319999999999993,
 81.234999999999999,
 79.828999999999994,
 75.635000000000005,
 64.061999999999998,
 79.441000000000003,
 56.728000000000002,
 65.554000000000002,
 74.852000000000004,
 50.728000000000002,
 72.390000000000001,
 73.004999999999995,
 52.295000000000002,
 49.579999999999998,
 59.722999999999999,
 50.43,
 80.653000000000006,
 44.741000000000007,
 50.651000000000003,
 78.552999999999997,
 72.960999999999999,
 72.888999999999996,
 65.152000000000001,
 46.462000000000003,
 55.322000000000003,
 78.781999999999996,
 48.328000000000003,
 75.748000000000005,
 78.272999999999996,
 76.486000000000004,
 78.331999999999994,
 54.790999999999997,
 72.234999999999999,
 74.994,
 71.338000000000022,
 71.878,
 51.578999999999994,
 58.039999999999999,
 52.947000000000003,
 79.313000000000002,
 80.656999999999996,
 56.734999999999999,
 59.448,
 79.406000000000006,
 60.021999999999998,
 79.483000000000004,
 70.259,
 56.006999999999998,
 46.388000000000012,
 60.915999999999997,
 70.198000000000008,
 82.207999999999998,
 73.338000000000022,
 81.757000000000005,
 64.698000000000008,
 70.650000000000006,
 70.963999999999999,
 59.545000000000002,
 78.885000000000005,
 80.745000000000005,
 80.546000000000006,
 72.566999999999993,
 82.602999999999994,
 72.534999999999997,
 54.109999999999999,
 67.296999999999997,
 78.623000000000005,
 77.588000000000022,
 71.992999999999995,
 42.591999999999999,
 45.677999999999997,
 73.951999999999998,
 59.443000000000012,
 48.302999999999997,
 74.241,
 54.466999999999999,
 64.164000000000001,
 72.801000000000002,
 76.194999999999993,
 66.802999999999997,
 74.543000000000006,
 71.164000000000001,
 42.082000000000001,
 62.069000000000003,
 52.906000000000013,
 63.784999999999997,
 79.762,
 80.203999999999994,
 72.899000000000001,
 56.866999999999997,
 46.859000000000002,
 80.195999999999998,
 75.640000000000001,
 65.483000000000004,
 75.536999999999978,
 71.751999999999995,
 71.421000000000006,
 71.688000000000002,
 75.563000000000002,
 78.097999999999999,
 78.746000000000024,
 76.441999999999993,
 72.475999999999999,
 46.241999999999997,
 65.528000000000006,
 72.777000000000001,
 63.061999999999998,
 74.001999999999995,
 42.568000000000012,
 79.971999999999994,
 74.662999999999997,
 77.926000000000002,
 48.158999999999999,
 49.338999999999999,
 80.941000000000003,
 72.396000000000001,
 58.555999999999997,
 39.613,
 80.884,
 81.701000000000022,
 74.143000000000001,
 78.400000000000006,
 52.517000000000003,
 70.616,
 58.420000000000002,
 69.819000000000003,
 73.923000000000002,
 71.777000000000001,
 51.542000000000002,
 79.424999999999997,
 78.242000000000004,
 76.384,
 73.747,
 74.248999999999995,
 73.421999999999997,
 62.698,
 42.383999999999993,
 43.487000000000002]

In [ ]:
gdp_cap=[974.58033839999996,
 5937.0295259999984,
 6223.3674650000003,
 4797.2312670000001,
 12779.379639999999,
 34435.367439999995,
 36126.492700000003,
 29796.048340000001,
 1391.253792,
 33692.605080000001,
 1441.2848730000001,
 3822.137084,
 7446.2988029999997,
 12569.851769999999,
 9065.8008250000003,
 10680.792820000001,
 1217.0329939999999,
 430.07069159999998,
 1713.7786860000001,
 2042.0952400000001,
 36319.235009999997,
 706.01653699999997,
 1704.0637240000001,
 13171.638849999999,
 4959.1148540000004,
 7006.5804189999999,
 986.14787920000003,
 277.55185870000003,
 3632.5577979999998,
 9645.06142,
 1544.7501119999999,
 14619.222719999998,
 8948.1029230000004,
 22833.308509999999,
 35278.418740000001,
 2082.4815670000007,
 6025.3747520000015,
 6873.2623260000009,
 5581.1809979999998,
 5728.3535140000004,
 12154.089749999999,
 641.36952360000021,
 690.80557590000001,
 33207.0844,
 30470.0167,
 13206.48452,
 752.74972649999995,
 32170.37442,
 1327.6089099999999,
 27538.41188,
 5186.0500030000003,
 942.6542111,
 579.23174299999982,
 1201.637154,
 3548.3308460000007,
 39724.978669999997,
 18008.944439999999,
 36180.789190000003,
 2452.210407,
 3540.6515639999998,
 11605.71449,
 4471.0619059999999,
 40675.996350000001,
 25523.277099999999,
 28569.719700000001,
 7320.8802620000015,
 31656.068060000001,
 4519.4611709999999,
 1463.249282,
 1593.06548,
 23348.139730000006,
 47306.989780000004,
 10461.05868,
 1569.3314419999999,
 414.5073415,
 12057.49928,
 1044.7701259999999,
 759.34991009999999,
 12451.6558,
 1042.581557,
 1803.151496,
 10956.991120000001,
 11977.57496,
 3095.7722710000007,
 9253.896111,
 3820.1752299999998,
 823.68562050000003,
 944.0,
 4811.0604290000001,
 1091.359778,
 36797.933319999996,
 25185.009109999999,
 2749.3209649999999,
 619.67689239999982,
 2013.9773049999999,
 49357.190170000002,
 22316.192869999999,
 2605.94758,
 9809.1856360000002,
 4172.8384640000004,
 7408.9055609999996,
 3190.4810160000002,
 15389.924680000002,
 20509.64777,
 19328.709009999999,
 7670.122558,
 10808.47561,
 863.08846390000019,
 1598.4350890000001,
 21654.83194,
 1712.4721360000001,
 9786.5347139999994,
 862.54075610000018,
 47143.179640000002,
 18678.314350000001,
 25768.257590000001,
 926.14106830000003,
 9269.6578079999999,
 28821.063699999999,
 3970.0954069999998,
 2602.3949950000001,
 4513.4806429999999,
 33859.748350000002,
 37506.419070000004,
 4184.5480889999999,
 28718.276839999999,
 1107.482182,
 7458.3963269999977,
 882.9699437999999,
 18008.509239999999,
 7092.9230250000001,
 8458.2763840000007,
 1056.3801209999999,
 33203.261279999999,
 42951.65309,
 10611.46299,
 11415.805689999999,
 2441.5764039999999,
 3025.3497980000002,
 2280.769906,
 1271.211593,
 469.70929810000007]

In [ ]:
plt.plot(gdp_cap,life_exp)

In [ ]:
plt.show()

In [ ]:
plt.scatter(gdp_cap, life_exp)
plt.xscale('log')
plt.xlabel('gdp')
plt.ylabel('life_expectancy')
plt.title('correlation between population and life expectancy')
plt.show()

In [ ]:
pop=[31.889923,
 3.6005229999999999,
 33.333216,
 12.420476000000001,
 40.301926999999999,
 20.434176000000001,
 8.199783,
 0.70857300000000001,
 150.448339,
 10.392226000000001,
 8.0783140000000007,
 9.1191519999999997,
 4.5521979999999997,
 1.6391309999999999,
 190.01064700000001,
 7.3228580000000001,
 14.326203,
 8.3905049999999992,
 14.131857999999999,
 17.696293000000001,
 33.390141,
 4.3690379999999998,
 10.238807,
 16.284741,
 1318.683096,
 44.227550000000001,
 0.71096000000000004,
 64.606758999999997,
 3.8006099999999998,
 4.1338840000000001,
 18.013408999999999,
 4.4933120000000004,
 11.416987000000001,
 10.228744000000001,
 5.4681199999999999,
 0.49637399999999998,
 9.3196220000000007,
 13.75568,
 80.264543000000003,
 6.9396880000000003,
 0.55120100000000005,
 4.9065849999999998,
 76.511887000000002,
 5.2384599999999999,
 61.083916000000002,
 1.4548669999999999,
 1.6883589999999999,
 82.400996000000006,
 22.873338,
 10.706289999999999,
 12.572927999999999,
 9.9478139999999993,
 1.4720409999999999,
 8.5028140000000008,
 7.4837629999999997,
 6.9804120000000003,
 9.9561080000000004,
 0.301931,
 1110.3963309999999,
 223.547,
 69.453569999999999,
 27.499638000000001,
 4.1090859999999996,
 6.426679,
 58.147733000000002,
 2.780132,
 127.467972,
 6.0531930000000003,
 35.610177,
 23.301725000000001,
 49.044789999999999,
 2.5055589999999999,
 3.921278,
 2.0126490000000001,
 3.1939419999999998,
 6.0369140000000003,
 19.167653999999999,
 13.327078999999999,
 24.821286000000001,
 12.031795000000001,
 3.2700650000000002,
 1.250882,
 108.700891,
 2.8741270000000001,
 0.68473600000000001,
 33.757174999999997,
 19.951656,
 47.761980000000001,
 2.0550799999999998,
 28.901789999999998,
 16.570613000000002,
 4.1157709999999996,
 5.6753559999999998,
 12.894864999999999,
 135.03116399999999,
 4.6279260000000004,
 3.2048969999999999,
 169.27061699999999,
 3.2421730000000002,
 6.6671469999999999,
 28.674757,
 91.077286999999998,
 38.518241000000003,
 10.642836000000001,
 3.942491,
 0.79809399999999997,
 22.276056000000001,
 8.8605879999999999,
 0.19957900000000001,
 27.601037999999999,
 12.267493,
 10.150264999999999,
 6.1445619999999996,
 4.5530090000000003,
 5.4475020000000001,
 2.0092449999999999,
 9.1187729999999991,
 43.997827999999998,
 40.448191000000001,
 20.378239000000001,
 42.292929000000001,
 1.1330659999999999,
 9.0310880000000004,
 7.5546610000000003,
 19.314747000000001,
 23.174294,
 38.13964,
 65.068149000000005,
 5.7015789999999997,
 1.056608,
 10.276158000000001,
 71.158647000000002,
 29.170397999999999,
 60.776237999999999,
 301.13994700000001,
 3.4474960000000001,
 26.084662000000002,
 85.262355999999997,
 4.018332,
 22.211742999999998,
 11.746034999999999,
 12.311143]

In [ ]:
plt.scatter(pop,life_exp)

In [ ]:
plt.show()

In [ ]:
plt.hist(life_exp)

In [ ]:
plt.show()

In [ ]:
plt.hist(life_exp,bins=10)

In [ ]:
plt.show()

In [ ]:
help(pd.read_csv)